/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsGroupIdRouteImport } from './routes/settings.$groupId'
import { Route as JoinInviteCodeRouteImport } from './routes/join/$inviteCode'
import { Route as GroupGroupIdRouteImport } from './routes/group/$groupId'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGroupIdRoute = SettingsGroupIdRouteImport.update({
  id: '/settings/$groupId',
  path: '/settings/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinInviteCodeRoute = JoinInviteCodeRouteImport.update({
  id: '/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupGroupIdRoute = GroupGroupIdRouteImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/settings/$groupId': typeof SettingsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/settings/$groupId': typeof SettingsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/settings/$groupId': typeof SettingsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/group/$groupId'
    | '/join/$inviteCode'
    | '/settings/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/group/$groupId'
    | '/join/$inviteCode'
    | '/settings/$groupId'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/group/$groupId'
    | '/join/$inviteCode'
    | '/settings/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  GroupGroupIdRoute: typeof GroupGroupIdRoute
  JoinInviteCodeRoute: typeof JoinInviteCodeRoute
  SettingsGroupIdRoute: typeof SettingsGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$groupId': {
      id: '/settings/$groupId'
      path: '/settings/$groupId'
      fullPath: '/settings/$groupId'
      preLoaderRoute: typeof SettingsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$inviteCode': {
      id: '/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof JoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$groupId': {
      id: '/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof GroupGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  GroupGroupIdRoute: GroupGroupIdRoute,
  JoinInviteCodeRoute: JoinInviteCodeRoute,
  SettingsGroupIdRoute: SettingsGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
