/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinInviteCodeRouteImport } from './routes/join/$inviteCode'
import { Route as GroupGroupIdRouteImport } from './routes/group/$groupId'
import { Route as GroupIdSettingsRouteImport } from './routes/$groupId.settings'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinInviteCodeRoute = JoinInviteCodeRouteImport.update({
  id: '/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupGroupIdRoute = GroupGroupIdRouteImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdSettingsRoute = GroupIdSettingsRouteImport.update({
  id: '/$groupId/settings',
  path: '/$groupId/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/$groupId/settings': typeof GroupIdSettingsRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/$groupId/settings': typeof GroupIdSettingsRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/$groupId/settings': typeof GroupIdSettingsRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/$groupId/settings'
    | '/group/$groupId'
    | '/join/$inviteCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/$groupId/settings'
    | '/group/$groupId'
    | '/join/$inviteCode'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/$groupId/settings'
    | '/group/$groupId'
    | '/join/$inviteCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  GroupIdSettingsRoute: typeof GroupIdSettingsRoute
  GroupGroupIdRoute: typeof GroupGroupIdRoute
  JoinInviteCodeRoute: typeof JoinInviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$inviteCode': {
      id: '/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof JoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$groupId': {
      id: '/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof GroupGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$groupId/settings': {
      id: '/$groupId/settings'
      path: '/$groupId/settings'
      fullPath: '/$groupId/settings'
      preLoaderRoute: typeof GroupIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  GroupIdSettingsRoute: GroupIdSettingsRoute,
  GroupGroupIdRoute: GroupGroupIdRoute,
  JoinInviteCodeRoute: JoinInviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
